export const carModels: Record<string, string[]> = {
  Toyota: [
    'Camry',
    'Corolla',
    'RAV4',
    'Prius',
    'Highlander',
    'Tacoma',
    'Tundra',
    '4Runner',
    'Sienna',
    'Supra',
    'Avalon',
    'C-HR',
    'Venza',
    'Sequoia',
    'Land Cruiser',
  ],
  Honda: [
    'Civic',
    'Accord',
    'CR-V',
    'Pilot',
    'Odyssey',
    'HR-V',
    'Fit',
    'Insight',
    'Clarity',
    'Legend',
  ],
  Nissan: [
    'Altima',
    'Sentra',
    'Rogue',
    'Pathfinder',
    'Murano',
    'Maxima',
    'Versa',
    'Kicks',
    'Titan',
    'Frontier',
    'Armada',
    '370Z',
    'GT-R',
    'Leaf',
  ],
  Hyundai: [
    'Elantra',
    'Sonata',
    'Tucson',
    'Santa Fe',
    'Kona',
    'Palisade',
    'Venue',
    'Veloster',
    'Ioniq',
    'Nexo',
    'Genesis G70',
    'Genesis G80',
    'Genesis G90',
  ],
  Kia: [
    'Forte',
    'Optima',
    'Sorento',
    'Sportage',
    'Telluride',
    'Soul',
    'Rio',
    'Stinger',
    'Carnival',
    'Niro',
    'EV6',
    'K5',
  ],
  Ford: [
    'F-150',
    'Mustang',
    'Explorer',
    'Focus',
    'Escape',
    'Edge',
    'Expedition',
    'Ranger',
    'Bronco',
    'Bronco Sport',
    'Maverick',
    'Transit',
    'Fusion',
    'GT',
  ],
  Chevrolet: [
    'Silverado',
    'Equinox',
    'Malibu',
    'Traverse',
    'Tahoe',
    'Suburban',
    'Camaro',
    'Corvette',
    'Colorado',
    'Bolt',
    'Blazer',
    'Trailblazer',
    'Impala',
    'Spark',
  ],
  Dodge: [
    'Challenger',
    'Charger',
    'Durango',
    'Journey',
    'Grand Caravan',
    'Viper',
    'Dart',
    'Ram 1500',
    'Ram 2500',
  ],
  Jeep: [
    'Wrangler',
    'Grand Cherokee',
    'Cherokee',
    'Compass',
    'Renegade',
    'Gladiator',
    'Wagoneer',
    'Grand Wagoneer',
  ],
  Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck'],
  BMW: [
    '3 Series',
    '5 Series',
    '7 Series',
    'X1',
    'X3',
    'X5',
    'X7',
    'i4',
    'i7',
    'i8',
    'Z4',
    'M2',
    'M3',
    'M4',
    'M5',
  ],
  Mercedes: [
    'A-Class',
    'C-Class',
    'E-Class',
    'S-Class',
    'GLA',
    'GLC',
    'GLE',
    'GLS',
    'AMG GT',
    'CLA',
    'CLS',
    'Maybach',
    'EQS',
    'EQE',
  ],
  Audi: [
    'A3',
    'A4',
    'A6',
    'A8',
    'Q3',
    'Q5',
    'Q7',
    'Q8',
    'e-tron',
    'e-tron GT',
    'RS6',
    'RS7',
    'R8',
    'TT',
  ],
  Volkswagen: [
    'Golf',
    'Jetta',
    'Passat',
    'Arteon',
    'Atlas',
    'Tiguan',
    'Taos',
    'ID.4',
    'ID.Buzz',
    'Beetle',
    'Polo',
    'T-Roc',
  ],
  Volvo: [
    'S60',
    'S90',
    'V60',
    'V90',
    'XC40',
    'XC60',
    'XC90',
    'C40',
    'Polestar 1',
    'Polestar 2',
  ],
  Porsche: [
    '911',
    'Taycan',
    'Panamera',
    'Cayenne',
    'Macan',
    'Boxster',
    'Cayman',
    '918 Spyder',
  ],
  Ferrari: [
    'Roma',
    'Portofino',
    'SF90',
    'F8 Tributo',
    '812 Superfast',
    '296 GTB',
    'LaFerrari',
  ],
  Lamborghini: ['Aventador', 'Huracán', 'Urus', 'Countach', 'Revuelto'],
  Maserati: ['Ghibli', 'Quattroporte', 'Levante', 'MC20', 'GranTurismo'],
  AstonMartin: ['DB11', 'Vantage', 'DBS', 'Valhalla', 'Valkyrie', 'DBX'],
  Subaru: [
    'Impreza',
    'Legacy',
    'Outback',
    'Forester',
    'Crosstrek',
    'Ascent',
    'BRZ',
    'WRX',
    'Solterra',
  ],
  Mazda: [
    'Mazda3',
    'Mazda6',
    'CX-3',
    'CX-5',
    'CX-9',
    'CX-30',
    'MX-5 Miata',
    'RX-8',
  ],
  Lexus: ['ES', 'LS', 'IS', 'RX', 'NX', 'UX', 'GX', 'LX', 'LC', 'RC'],
  Infiniti: ['Q50', 'Q60', 'Q70', 'QX50', 'QX55', 'QX60', 'QX80'],
  Acura: ['TLX', 'RLX', 'RDX', 'MDX', 'NSX'],
};

export const makes = Object.keys(carModels);
